name: Build

on:
  push:
    branches: [ main, experimental ]

  pull_request:
    branches: [ main, experimental ]

  workflow_dispatch:

  workflow_call:
    inputs:
      tag_name:
        description: "Release tag"
        required: false
        type: string
      prerelease:
        description: "Prerelease flag"
        required: false
        type: boolean
      custom_message:
        description: "Release message"
        required: false
        type: string

jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        run: |
          sudo apt-get update
          sudo apt-get install -y libvlc-dev libvlccore-dev
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          chmod +x ./setup/unix.sh
          sh ./setup/unix.sh

      - name: Skip SScript setup mode
        run: echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Create Version Tag
        run: |
          if [ -n "${{ inputs.tag_name }}" ]; then
            echo "${{ inputs.tag_name }}" > VERSION
          else
            echo "${{ github.run_id }}" > VERSION
          fi

      - name: Compile Linux
        run: |
          haxelib run lime build Project.xml linux \
          --app-version="4.0.0-${{ github.run_id }}" \
          -D officialBuild

      - name: Publish Linux Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linuxBuild
          path: export/release/linux/bin

  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Haxelib
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp
          call setup/windows.bat

      - name: Skip SScript setup mode
        shell: cmd
        run: echo oy9:showMacroty8:loopCosti25y10:includeAllfg >> %USERPROFILE%\settings.cocoa

      - name: Create Version Tag
        shell: bash
        run: |
          if [ -n "${{ inputs.tag_name }}" ]; then
            echo "${{ inputs.tag_name }}" > VERSION
          else
            echo "${{ github.run_id }}" > VERSION
          fi

      - name: Compile Windows
        run: |
          haxelib run lime build windows \
          --app-version="4.0.0-${{ github.run_id }}" \
          -D officialBuild

      - name: Publish Windows Artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
